### ISSUE TITLE
What is the difference between GIS commands and GIS tools?

### ISSUE THREAD

**Issue by UbaydullohML** [abhyudaya12/Kaggle-Learn#23]

**Comment by abhyudaya12** [comment]
The key difference between GIS commands and GIS tools lies in how you interact with them to perform a specific task within a GIS software:

GIS Commands: These are specific instructions you type directly into a command line interface within the software.  They are text-based and require knowledge of the exact format and syntax for each command.

GIS Tools:  These are typically buttons, menus, or icons you click on within the graphical user interface (GUI) of the software. They are more user-friendly and often involve interacting with the map display itself, like selecting features or drawing areas.

**Comment by UbaydullohML** [comment]
Thanks
